version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: aff_video_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=aff_video
    restart: unless-stopped

volumes:
  mongo_data:
